package monadbft_test

// Cross-language conformance: every vector in testdata/vectors.txt was
// generated by the Rust monad-bft code (fixture-gen). The Go port must
// produce byte-identical encodings and equivalent signature behavior.

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"os"
	"strings"
	"testing"

	"github.com/abhijitkrm/monadbft-go/crypto"
	"github.com/abhijitkrm/monadbft-go/cstypes"
	"github.com/abhijitkrm/monadbft-go/exec"
	"github.com/abhijitkrm/monadbft-go/messages"
	"github.com/abhijitkrm/monadbft-go/sigcol"
	"github.com/abhijitkrm/monadbft-go/testutil"
	"github.com/abhijitkrm/monadbft-go/types"
	"github.com/abhijitkrm/monadbft-go/validator"
	"github.com/zeebo/blake3"
)

func loadVectors(t *testing.T) map[string][]byte {
	t.Helper()
	f, err := os.Open("testdata/vectors.txt")
	if err != nil {
		t.Fatalf("open vectors: %v", err)
	}
	defer f.Close()
	out := map[string][]byte{}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, ": ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad vector line: %q", line)
		}
		b, err := hex.DecodeString(parts[1])
		if err != nil {
			t.Fatalf("bad hex for %s: %v", parts[0], err)
		}
		out[parts[0]] = b
	}
	return out
}

func TestBlake3(t *testing.T) {
	v := loadVectors(t)
	if got := blake3.Sum256([]byte("hello world")); !bytes.Equal(got[:], v["blake3_hello"]) {
		t.Fatalf("blake3 mismatch: got %x", got)
	}
}

func TestSecpSignRecover(t *testing.T) {
	v := loadVectors(t)
	kp := testutil.GetKey(22354)
	if got := kp.PubKey().Bytes(); !bytes.Equal(got, v["secp_pubkey_22354"]) {
		t.Fatalf("pubkey mismatch:\n got %x\nwant %x", got, v["secp_pubkey_22354"])
	}
	sig := kp.Sign(crypto.DomainConsensusMessage, []byte("hello world"))
	if !bytes.Equal(sig[:], v["secp_sig_hello"]) {
		t.Fatalf("sig mismatch:\n got %x\nwant %x", sig[:], v["secp_sig_hello"])
	}
	rec, err := sig.RecoverPubKey(crypto.DomainConsensusMessage, []byte("hello world"))
	if err != nil {
		t.Fatalf("recover: %v", err)
	}
	if !bytes.Equal(rec[:], v["secp_recovered_pubkey"]) {
		t.Fatalf("recovered pubkey mismatch")
	}
	if !sig.Verify(crypto.DomainConsensusMessage, []byte("hello world"), kp.PubKey()) {
		t.Fatal("verify failed")
	}
}

func TestBlsSignVerify(t *testing.T) {
	v := loadVectors(t)
	kp := testutil.GetCertKey(22354)
	if got := kp.PubKey().Compress(); !bytes.Equal(got, v["bls_pubkey_22354_compressed"]) {
		t.Fatalf("bls pubkey mismatch:\n got %x\nwant %x", got, v["bls_pubkey_22354_compressed"])
	}
	sig := kp.Sign(crypto.DomainVote, []byte("vote-msg"))
	if !bytes.Equal(sig.Compress(), v["bls_sig_vote_msg"]) {
		t.Fatalf("bls sig mismatch:\n got %x\nwant %x", sig.Compress(), v["bls_sig_vote_msg"])
	}
	if !sig.Verify(crypto.DomainVote, []byte("vote-msg"), kp.PubKey()) {
		t.Fatal("bls verify failed")
	}
}

func TestVoteRLP(t *testing.T) {
	v := loadVectors(t)
	vote := cstypes.Vote{
		ID:    types.BlockId{0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a},
		Round: 8,
		Epoch: 1,
	}
	if got := vote.EncodeRLP(nil); !bytes.Equal(got, v["vote_rlp"]) {
		t.Fatalf("vote rlp mismatch:\n got %x\nwant %x", got, v["vote_rlp"])
	}
	// decode round-trip
	var d cstypes.Vote
	if err := d.DecodeRLP(streamOf(v["vote_rlp"])); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if d != vote {
		t.Fatalf("round-trip mismatch")
	}
}

func TestTimeoutInfoRLP(t *testing.T) {
	v := loadVectors(t)
	ti := cstypes.TimeoutInfo{Epoch: 12, Round: 123, HighQcRound: 0, HighTipRound: 0}
	if got := ti.EncodeRLP(nil); !bytes.Equal(got, v["timeout_info_rlp"]) {
		t.Fatalf("timeout info mismatch:\n got %x\nwant %x", got, v["timeout_info_rlp"])
	}
}

func TestGenesisQC(t *testing.T) {
	v := loadVectors(t)
	qc := cstypes.GenesisQC()
	if got := qc.EncodeRLP(nil); !bytes.Equal(got, v["genesis_qc_rlp"]) {
		t.Fatalf("genesis qc mismatch:\n got %x\nwant %x", got, v["genesis_qc_rlp"])
	}
}

func TestVoteMessageRLP(t *testing.T) {
	v := loadVectors(t)
	kp := testutil.GetCertKey(22354)
	vote := cstypes.Vote{
		ID:    bytes32(0x2a),
		Round: 8,
		Epoch: 1,
	}
	vm := messages.NewVoteMessage(vote, kp)
	if got := vm.EncodeRLP(nil); !bytes.Equal(got, v["vote_message_rlp"]) {
		t.Fatalf("vote message mismatch:\n got %x\nwant %x", got, v["vote_message_rlp"])
	}
	// verify sig against cert pubkey
	if !vm.Sig.Verify(crypto.DomainVote, vote.EncodeRLP(nil), kp.PubKey()) {
		t.Fatal("vote message sig verify failed")
	}
}

func TestTimeoutMessageRLP(t *testing.T) {
	v := loadVectors(t)
	kp := testutil.GetCertKey(22354)
	ti := cstypes.TimeoutInfo{Epoch: 12, Round: 123, HighQcRound: 0, HighTipRound: 0}
	tm := messages.NewTimeoutMessage(kp, ti, cstypes.HighExtendQc(cstypes.GenesisQC()), true, nil)
	if got := tm.EncodeRLP(nil); !bytes.Equal(got, v["timeout_message_rlp"]) {
		t.Fatalf("timeout message mismatch:\n got %x\nwant %x", got, v["timeout_message_rlp"])
	}
	// decode round-trip through the message layer
	var d messages.TimeoutMessage
	err := decodeExact(v["timeout_message_rlp"], func(s *streamT) error {
		return d.DecodeRLP(s, exec.Mock)
	})
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	if d.Timeout.TmInfo != ti {
		t.Fatalf("tminfo mismatch after decode")
	}
}

func TestSigCollection(t *testing.T) {
	v := loadVectors(t)
	// 4 validators; signers at insertion indices 0 and 2 → sorted positions
	// determined by compressed-pubkey ordering (fixture: bits {1,3} → 0x05).
	keys := make([]*crypto.BlsKeyPair, 4)
	nodes := make([]types.NodeId, 4)
	for i := range keys {
		keys[i] = testutil.GetCertKey(100 + uint64(i))
		nodes[i] = types.NewNodeId(testutil.GetKey(200 + uint64(i)).PubKey())
	}
	// sorted nodeids must match the fixture order
	sorted := append([]types.NodeId(nil), nodes...)
	sortNodeIds(sorted)
	for i := range sorted {
		if got := uncompressedPubkey(sorted[i].PubKey); !bytes.Equal(got, v["sorted_nodeid_"+itoa(i)]) {
			t.Fatalf("sorted nodeid %d mismatch:\n got %x\nwant %x", i, got, v["sorted_nodeid_"+itoa(i)])
		}
	}
	var entries []struct {
		NodeId     types.NodeId
		CertPubKey crypto.BlsPubKey
	}
	for i := range nodes {
		entries = append(entries, struct {
			NodeId     types.NodeId
			CertPubKey crypto.BlsPubKey
		}{nodes[i], keys[i].PubKey()})
	}
	mapping := validator.NewValidatorMapping(entries)

	vote := cstypes.Vote{ID: bytes32(0x2a), Round: 8, Epoch: 1}
	voteBytes := vote.EncodeRLP(nil)
	var sigs []sigcol.NodeSig
	for _, i := range []int{0, 2} {
		sigs = append(sigs, sigcol.NodeSig{
			NodeId: nodes[i],
			Sig:    keys[i].Sign(crypto.DomainVote, voteBytes),
		})
	}
	sc, err := sigcol.New(crypto.DomainVote, sigs, mapping, voteBytes)
	if err != nil {
		t.Fatalf("sigcol new: %v", err)
	}
	if got := sc.EncodeRLP(nil); !bytes.Equal(got, v["sig_collection_rlp"]) {
		t.Fatalf("sig collection mismatch:\n got %x\nwant %x", got, v["sig_collection_rlp"])
	}
	signers, err := sc.Verify(crypto.DomainVote, mapping, voteBytes)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if len(signers) != 2 {
		t.Fatalf("expected 2 signers, got %d", len(signers))
	}
}

func TestLeaderElection(t *testing.T) {
	v := loadVectors(t)
	// validators = get_key(300+i), stake = i+1; member order = sorted NodeId
	var vals []validator.ValidatorData
	nodes := map[[33]byte]types.NodeId{}
	for i := 0; i < 4; i++ {
		nid := types.NewNodeId(testutil.GetKey(300 + uint64(i)).PubKey())
		vals = append(vals, validator.ValidatorData{
			NodeId: nid,
			Stake:  types.StakeFromUint64(uint64(i + 1)),
		})
		nodes[[33]byte(nid.PubKey)] = nid
	}
	vs, err := validator.NewValidatorSet(vals)
	if err != nil {
		t.Fatal(err)
	}
	// verify member ordering matches Rust BTreeMap order
	for i, m := range vs.Members() {
		want := v["vs_member_"+itoa(i)]
		if !bytes.Equal(m.PubKey[:], want) {
			t.Fatalf("vs member %d: got %x want %x", i, m.PubKey, want)
		}
	}
	election := validator.WeightedRoundRobin{}
	for r := uint64(0); r < 8; r++ {
		got := election.GetLeader(types.Round(r), vs.Members(), func(id types.NodeId) types.Stake {
			s, _ := vs.StakeOf(id)
			return s
		})
		// fixture line: "leader_round_r: <pubkey> (pos N)"
		line := v["leader_round_"+itoa(int(r))+"_pk"]
		want := v["leader_round_"+itoa(int(r))]
		if line == nil && want == nil {
			t.Fatalf("missing vector for round %d", r)
		}
		if !bytes.Equal(got.PubKey[:], want) {
			t.Fatalf("round %d leader: got %x want %x", r, got.PubKey, want)
		}
	}
}

func TestConsensusMessageEnvelope(t *testing.T) {
	v := loadVectors(t)
	// rebuild the exact fixture: ConsensusMessage{version:1, Vote(vote)} signed
	// by get_key(42), where vote = {0x2a.., round 8, epoch 1}
	kp := testutil.GetKey(42)
	bk := testutil.GetCertKey(22354)
	vote := cstypes.Vote{ID: bytes32(0x2a), Round: 8, Epoch: 1}
	vm := messages.NewVoteMessage(vote, bk)
	cm := messages.ConsensusMessage{
		Version: 1,
		Message: messages.ProtocolMessage{Kind: messages.PMVote, Vote: &vm},
	}
	signed := messages.Sign(cm, kp)
	if got := signed.Message.EncodeRLP(nil); !bytes.Equal(got, v["consensus_msg_envelope_rlp"]) {
		t.Fatalf("envelope mismatch:\n got %x\nwant %x", got, v["consensus_msg_envelope_rlp"])
	}
	if !bytes.Equal(signed.Author.PubKey[:], v["consensus_msg_author"]) {
		t.Fatalf("author mismatch: got %x want %x", signed.Author.PubKey, v["consensus_msg_author"])
	}
	// decode + verify round trip
	var u messages.Unverified
	if err := decodeExact(v["consensus_msg_envelope_rlp"], func(s *streamT) error {
		return u.DecodeRLP(s, exec.Mock)
	}); err != nil {
		t.Fatalf("decode envelope: %v", err)
	}
	vf, err := u.Verify()
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if vf.Author != signed.Author {
		t.Fatal("author mismatch after verify")
	}
	if vf.Message.Obj.Message.Kind != messages.PMVote {
		t.Fatal("wrong message kind")
	}
}
