package raptor

// Symbol-level wire-conformance test: encoded symbols produced by the Go
// encoder must equal the reference Rust encoder's output bit-for-bit.
// Fixtures were generated by monad-bft/monad-raptor (Encoder over
// SYMBOL_LEN=16) and checked into testdata/raptor_fixtures.txt as lines:
//
//	src_len k esi symbol_hex
//
// where src is the deterministic xorshift64* stream seeded 0x243F6A8885A308D3.

import (
	"encoding/hex"

	"os"
	"strconv"
	"strings"
	"testing"
)

var fixtureSrcLens = []int{0, 1, 3, 4, 7, 16, 17, 40, 100, 255, 1024, 5000}

func fixtureSrc(srcLen int) []byte {
	offset := 0
	for _, l := range fixtureSrcLens {
		if l == srcLen {
			break
		}
		offset += l
	}

	state := uint64(0x243F6A8885A308D3)
	next := func() byte {
		state ^= state << 13
		state ^= state >> 7
		state ^= state << 17
		return byte(state)
	}
	for i := 0; i < offset; i++ {
		next()
	}
	src := make([]byte, srcLen)
	for i := range src {
		src[i] = next()
	}
	return src
}

func TestEncoderConformance(t *testing.T) {
	data, err := os.ReadFile("../testdata/raptor_fixtures.txt")
	if err != nil {
		t.Fatalf("read fixtures: %v", err)
	}

	const fixtureSymbolLen = 16

	// Cache encoders per src_len.
	encoders := map[int]*Encoder{}

	n := 0
	for _, line := range strings.Split(strings.TrimSpace(string(data)), "\n") {
		f := strings.Fields(line)
		if len(f) != 4 {
			t.Fatalf("malformed fixture line: %q", line)
		}
		srcLen, _ := strconv.Atoi(f[0])
		k, _ := strconv.Atoi(f[1])
		esi, _ := strconv.Atoi(f[2])
		want, err := hex.DecodeString(f[3])
		if err != nil {
			t.Fatalf("bad hex in fixture: %v", err)
		}

		enc, ok := encoders[srcLen]
		if !ok {
			enc, err = NewEncoder(fixtureSrc(srcLen), fixtureSymbolLen)
			if err != nil {
				t.Fatalf("NewEncoder(src_len=%d): %v", srcLen, err)
			}
			if got := enc.NumSourceSymbols(); got != k {
				t.Fatalf("src_len=%d: K mismatch: got %d, fixture %d", srcLen, got, k)
			}
			encoders[srcLen] = enc
		}

		got := make([]byte, fixtureSymbolLen)
		enc.EncodeSymbol(got, esi)
		if !equalBytes(got, want) {
			t.Fatalf("src_len=%d esi=%d: symbol mismatch:\n got %x\nwant %x",
				srcLen, esi, got, want)
		}
		n++
	}
	if n == 0 {
		t.Fatal("no fixtures replayed")
	}
	t.Logf("replayed %d fixtures, all byte-exact", n)
}

func equalBytes(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
